site_name: <Projekt Name> - Makerspace Repair-Café Hilpoltstein
site_url: https://makes-hacks-hip.github.io/<Repository Name>/
nav:
    - Repair-Café: https://www.repaircafe-hilpoltstein.de
    - Makerspace: https://makes-hacks-hip.de
    - Makerspace@Github: https://makes-hacks-hip.github.io
theme: readthedocs
